
Months = {
    "Jan": "01",
    "Fev": "02",
    "Mar": "03",
    "Abr": "04",
    "Mai": "05",
    "Jun": "06",
    "Jul": "07",
    "Ago": "08",
    "Set": "09",
    "Out": "10",
    "Nov": "11",
    "Dez": "12"
}

Ufs = {
'ACRE':'AC',
'ALAGOAS':'AL',
'AMAPÁ':'AP',
'AMAZONAS':'AM',
'BAHIA':'BA',
'CEARÁ':'CE',
'DISTRITO FEDERAL':'DF',
'ESPÍRITO SANTO':'ES',
'GOIÁS':'GO',
'MARANHÃO':'MA',
'MATO GROSSO':'MT',
'MATO GROSSO DO SUL':'MS',
'MINAS GERAIS':'MG',
'PARÁ':'PA',
'PARAÍBA':'PB',
'PARANÁ':'PR',
'PERNAMBUCO':'PE',
'PIAUÍ':'PI',
'RIO DE JANEIRO':'RJ',
'RIO GRANDE DO NORTE':'RN',
'RIO GRANDE DO SUL':'RS',
'RONDÔNIA':'RO',
'RORAIMA':'RR',
'SANTA CATARINA':'SC',
'SÃO PAULO':'SP',
'SERGIPE':'SE',
'TOCANTINS':'TO'
}